### ISSUE TITLE
DevProxy

### ISSUE THREAD

**Issue by AngelMunoz** [AngelMunoz/Perla#10]
Offer a proxy configuration for the dev server so users can decide where to redirect their API calls

I'm not familiar with this area so anyone wants to take a look I would welcome it

**Comment by AngelMunoz** [comment]
Relevant info https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0

Also there's a CustomCE method in this repository 

https://github.com/ChrSteinert/Saturn.Proxy

**Comment by AngelMunoz** [comment]
relevant
https://github.com/natemcmaster/dotnet-serve/pull/85

**Comment by AngelMunoz** [comment]
relevant x2
https://github.com/microsoft/reverse-proxy/issues/1380

**Comment by bbhxwl** [comment]
> relevant x2 [microsoft/reverse-proxy#1380](https://github.com/microsoft/reverse-proxy/issues/1380)

Maybe this project is not perfect. It is in the early stage of development. I look forward to gradually improving it. If only reverse proxy could be as simple as nginx.

**Comment by AngelMunoz** [comment]
This is out in [v0.16.0](https://github.com/AngelMunoz/Perla/releases/tag/v.0.16.0)
