### ISSUE TITLE
Playwright is installed even though I said no

### ISSUE THREAD

**Issue by nojaf** [AngelMunoz/Perla#102]
![image](https://user-images.githubusercontent.com/2621499/228037518-71d06f50-8a26-4431-9615-cbfd952141e4.png)

**Comment by AngelMunoz** [comment]
This was miss named, it was not an option to not install playwright but the dependencies of playwright (for some Linux envs) this has been reworked for the setup command and it should not install playwright by default until we make the "testing command stable" this change is out in beta 13

**Comment by AngelMunoz** [comment]
this is available in beta 16 please see #107 for more information
