### ISSUE TITLE
Remove required argument from the template command

### ISSUE THREAD

**Issue by AngelMunoz** [AngelMunoz/Perla#120]
**Is your feature request related to a problem? Please describe.**

Running `perla templates` without arguments should show the table of the current templates available for perla's scaffolding features, but currently it requires an argument (namely the template name for the rest of the operations related to templates)

**Describe the solution you'd like**
We should make the required templateName optional, and just default to show the list of existing templates available for perla.

In regards of the information of the table it currently displays the following columns:

- Name
- Group
- Belongs To
- Parent Location
- Last Update

Taking feedback from #118 I'm considering using the following columns instead:

- Name
- perla new <project> -t
- perla new <project> -id
- perla new <project> -tn

e.g.

| Name | perla new <project> -t | perla new <project> -id | perla new <project> -tn |
|--------|--------|--------|--------|
| Fable Feliz | perla new -t ff | perla new -id perla.templates.fable.feliz | perla new -tn AngelMunoz/perla-templates/fable-feliz |
| Fable Sutil | perla new -t fs | perla new -id perla.templates.fable.sutil | perla new -tn perla-templates/fable-sutil | 

One potential issue here is that `-tn` can be provided partially or fully annotated.
The shorthand form (no GH user) in the example it works because there is a single repository with the `perla-templates` name, the following wouldn't work and you will need to provide the full name: 

- AngelMunoz/perla-templates
- fable-compiler/perla-templates

So we could remove that option completely at least for users

**Describe alternatives you've considered**
A Wizard-like experience for templates as well, `perla template` runs a wizard-like experience just as `perla new` does
- What would you like to do?
  - List Templates
  - Add Template
  - Update Template
  - Remove Template
  - Describe Template
  - Describe Repository

**Additional context**

Reported in #118 
cc @kaeedo

**Comment by kaeedo** [comment]
Question: What's the idea behind the group ID of the templates? It seems like overkill to have three different ways of specifying a template, especially when two of them are rather long. Having the shortname makes sense IMO, and having the full repository name also makes sense, because then you automatically know the source.

Would it make sense to remove the id option?

**Comment by AngelMunoz** [comment]
The original way to add templates was the `-tn` flag, and there were no wizard-like commands, so it was very annoying to type the full name, but I'm settled on removing hiding that flag now as either group, and -t are good enough for this kind of use case

As for why I want to offer both -id and -t flags:

-t is a quick short string which may not be explicative the example is `-t ff` if you're familiar then `ff` makes sense to `fable-feliz` but for other people it might not be as straight forward, the id flag for me means a clear way to differentiate templates even if their `-t` counterparts might look like the same for other templates

Having both doesn't affect us much, and `-id` fills what `-tn` was used for (a fully qualified way to ensure the template you selected is the one you actually want)

**Comment by kaeedo** [comment]
Thanks for the explanation. In that case i'll also do this change, and at the same time remove the `-tn` option. Sound good?

**Comment by AngelMunoz** [comment]
Yep, that sounds good!

**Comment by AngelMunoz** [comment]
This is out in beta 21!
