### ISSUE TITLE
program to append a content in bash script

### ISSUE THREAD

**Issue by skaft21** [AngelMunoz/Perla#41]
In the Bash script, write a simple program that first creates a new file called myfile.txt, then append the string "Hello world" to it. Then print out the size in bytes of myfile.txt.

**Comment by skaft21** [comment]
please help

**Comment by AngelMunoz** [comment]
I don't know how to write bash scripts, please refrain from opening issues unrelated to this project

**Comment by AngelMunoz** [comment]
I don't know how to write bash scripts, please refrain from opening issues unrelated to this project
