### ISSUE TITLE
useSSL and port is not respected

### ISSUE THREAD

**Issue by nojaf** [AngelMunoz/Perla#68]
**Describe the bug**
When both `useSSL` and `port` are listed, the SSL port is one higher.

**To Reproduce**
perla.jsonc
```json
  "devServer": {
    "useSSL": true,
    "mountDirectories": {
      "./src": "/src",
      "./images": "/images"
    },
    "port": 8900,
    "host":"localhost"
  },
```
![image](https://user-images.githubusercontent.com/2621499/150860746-5325f79f-6639-4780-8a5b-0a3da8485416.png)

**Expected behavior**
https://localhost:8900 would work, instead `http://` is listed on port 8900.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version v0.19.0

**Additional context**
The `"host"` isn't relevant in this issue, but I propose it to be the default actually.
https://127.0.0.1:8901 will not work in the browser, https://localhost:8901 will.

**Comment by AngelMunoz** [comment]
Thanks for reporting this

**Comment by nojaf** [comment]
Thank you for fixing this!
