### ISSUE TITLE
style sheet only reloads once

### ISSUE THREAD

**Issue by nojaf** [AngelMunoz/Perla#70]
**Describe the bug**
The browser doesn't always reload when making CSS changes.

**To Reproduce**

I'm watching a folder where I have a stylesheet:
```
  "devServer": {
    "port": 8900,
    "mountDirectories": {
      "./images": "/images",
      "./styles": "/styles",
      "./src": "/src"
    },
    "useSSL": true,
    "watchConfig": {
        "directories": ["./src", "./styles"]
    }
  },
```

I'm importing this in Fable `importSideEffects "../styles/style.css"`.
After the first change, the browser no longer reloads.

**Expected behavior**
The browser reloads on each CSS change.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Latest Chrome
 - Version: Perla 0.20.0

**Additional context**
The server does pick up the change:
```
info: Perla:SSE[0]
      CSS File Changed: style.css
info: Perla:SSE[0]
      CSS File Changed: style.css
info: Perla:SSE[0]
      CSS File Changed: style.css
info: Perla:SSE[0]
      CSS File Changed: style.css
```

but the browser only reloads once.

**Comment by AngelMunoz** [comment]
Hey there, Welcome back!
CSS changes imported this way should not reload the whole page instead they are applied as "Hot Reload" and the changes should be instant.

I've seen the issue you mention, I'm guessing it has to do with windows paths (`/` vs `\`)
I'll get to fix that

Also I'd ask the following

- Do you expect a full page reload? or is it good the way it is (once it's properly working of course)?

**Comment by nojaf** [comment]
Oh, yeah "hot reload" would work just as fine.
Thank you for looking into this.

**Comment by AngelMunoz** [comment]
https://github.com/AngelMunoz/Perla/releases/tag/v0.20.1
https://www.nuget.org/packages/Perla/0.20.1

Just give NuGet a chance to list it, and it'll be ready, otherwise binaries are out as well

**Comment by nojaf** [comment]
Wow, super fast 🔥 Thanks, I'll give it a shot.

**Comment by nojaf** [comment]
Tried out the new release, totally works! Thanks again!
