### ISSUE TITLE
Batch file changes

### ISSUE THREAD

**Issue by nojaf** [AngelMunoz/Perla#72]
**Is your feature request related to a problem? Please describe.**

I'm currently working with Fable and my project structure is the following:
`/fsharp/App.fsproj`, compiling the files to `/src`

```jsonc
  "fable": {
    "project": "./fsharp/App.fsproj",
    "extension": ".js",
    "outDir": "./src"
  },
  "devServer": {
    "port": 8900,
    "mountDirectories": {
      "./images": "/images",
      "./styles": "/styles",
      "./src": "/src"
    },
    "useSSL": true,
    "watchConfig": {
        "directories": ["./src", "./styles"]
    }
  },
```

Sometimes this can trigger multiple file changes, I would propose to batch these for the same file extension.

**Describe the solution you'd like**

Could we do something clever with the observable stream in

https://github.com/AngelMunoz/Perla/blob/5dc7ef7a66fa4f33cd225538b709db582b8bdc47/src/Perla.Lib/Server.fs#L284-L287

Just so changes in the same timeframe (f.ex. 400ms) are processed as one update.

**Describe alternatives you've considered**

I guess you could debounce as well on the service worker side, though more control could be added on the server I think.

**Additional context**

**Comment by AngelMunoz** [comment]
thanks for mentioning this one, yeah maybe with [throttleComputed](https://github.com/fsprojects/FSharp.Control.Reactive/blob/master/src/FSharp.Control.Reactive/Observable.fs#L1889) or similar we could try to throttle based on file extension

I'll try to check this one in the next few days

**Comment by AngelMunoz** [comment]
Hey there! just cleaning up a bit, this should already be in I'll close this
